[package]
name = "jex-sc-staking-v2"
version = "0.0.0"
authors = ["Aurélien Passion <aurelien.passion@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies.multiversx-sc-scenario]
version = "0.53.2"

[dependencies.multiversx-sc]
version = "0.53.2"
