// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    jex_sc_staking_v2
    (
        configure
        configureToken
        initRound
        snapshot
        fundRewards
        prepareRewards
        distribute
        getState
        getCurrentRound
        getCurrentRoundRewards
        getRewardsForRound
        getAllAddresses
        getNbAddresses
        getSnapshotTotalBalance
        getSharesOfAddress
        getTokenThresholds
    )
}

elrond_wasm_node::wasm_empty_callback! {}
